export interface MDCodeClinical {
    id: string;
    name: string;
    indices: { right: number | number[]; left: number | number[] };
    clinical: {
        depth: string;
        tool: "Needle" | "Cannula";
        active_volume: string;
        technique: string;
        alert: boolean;
        alert_reason?: string;
    };
    purpose?: string;
}

export const MD_CODES_CLINICAL: Record<string, MDCodeClinical[]> = {
    foundation: [
        {
            id: "Ck1",
            name: "Zygomatic Arch",
            indices: { right: 116, left: 345 },
            clinical: {
                depth: "Supraperiosteal",
                tool: "Needle",
                active_volume: "0.3",
                technique: "Bolus",
                alert: false,
            },
            purpose: "Lateral Lifting & Anchorage",
        },

        {
            id: "Ck2",
            name: "Zygomatic Eminence",
            indices: { right: [50, 118], left: [280, 347] },
            clinical: {
                depth: "Supraperiosteal",
                tool: "Needle",
                active_volume: "0.2",
                technique: "Bolus",
                alert: true,
                alert_reason: "A. Zigomaticofacial",
            },
            purpose: "Projection & Lifting",
        },
        {
            id: "Ck3",
            name: "Anteromedial Cheek",
            indices: { right: 100, left: 329 },
            clinical: {
                depth: "Supraperiosteal",
                tool: "Needle",
                active_volume: "0.3",
                technique: "Bolus",
                alert: true,
                alert_reason: "A. Infraorbital",
            },
            purpose: "Volume Replacement",
        },
        {
            id: "Ck4",
            name: "Lateral Lower Cheek",
            indices: { right: [123, 132], left: [352, 361] },
            clinical: {
                depth: "Subcutâneo",
                tool: "Cannula",
                active_volume: "0.5",
                technique: "Fanning",
                alert: true,
                alert_reason: "G. Parótida",
            },
            purpose: "Lateral Contouring",
        },
        {
            id: "Ck5",
            name: "Submalar / Bucal",
            indices: { right: 205, left: 425 },
            clinical: {
                depth: "Subcutâneo",
                tool: "Cannula",
                active_volume: "0.5",
                technique: "Fanning",
                alert: true,
                alert_reason: "N. Bucal / V. Facial",
            },
            purpose: "Hollow Cheek Correction",
        },
    ],
    contour: [
        {
            id: "T1",
            name: "Têmpora Anterior",
            indices: { right: 71, left: 301 },
            clinical: {
                depth: "Supraperiosteal",
                tool: "Needle",
                active_volume: "0.5",
                technique: "Bolus",
                alert: true,
                alert_reason: "A. Temporal Profunda",
            },
            purpose: "Temple Filling",
        },
        {
            id: "T2",
            name: "Têmpora Posterior",
            indices: { right: 21, left: 251 },
            clinical: {
                depth: "Supraperiosteal",
                tool: "Needle",
                active_volume: "0.5",
                technique: "Bolus",
                alert: true,
                alert_reason: "A. Temporal Profunda",
            },
            purpose: "Temple Lifting",
        },
        {
            id: "F1",
            name: "Testa Medial",
            indices: { right: 67, left: 297 },
            clinical: { depth: "Supraperiosteal", tool: "Cannula", active_volume: "0.5", technique: "Cannula", alert: true, alert_reason: "A. Supraorbital" },
            purpose: "Forehead Volume",
        },
        {
            id: "F2",
            name: "Testa Lateral",
            indices: { right: 103, left: 332 },
            clinical: { depth: "Supraperiosteal", tool: "Cannula", active_volume: "0.5", technique: "Cannula", alert: true, alert_reason: "A. Temporal Superficial" },
            purpose: "Forehead Volume",
        },
        {
            id: "F3",
            name: "Testa Central",
            indices: { right: 10, left: 10 },
            clinical: { depth: "Supraperiosteal", tool: "Cannula", active_volume: "0.5", technique: "Cannula", alert: true, alert_reason: "A. Supratroclear" },
            purpose: "Forehead Volume",
        },
        {
            id: "C1",
            name: "Ângulo Labiomentoniano",
            indices: { right: [176, 202], left: [406, 418] },
            clinical: {
                depth: "Subcutâneo",
                tool: "Cannula",
                active_volume: "0.5",
                technique: "Fanning",
                alert: false,
            },
            purpose: "Lateral Chin Support",
        },
        {
            id: "C2",
            name: "Ápice do Mento",
            indices: { right: 152, left: 152 },
            clinical: {
                depth: "Subcutâneo/Supra.",
                tool: "Needle",
                active_volume: "0.3",
                technique: "Bolus",
                alert: false,
            },
            purpose: "Chin Elongation",
        },
        {
            id: "C3",
            name: "Mento Anterior",
            indices: { right: 201, left: 421 },
            clinical: {
                depth: "Supraperiosteal",
                tool: "Needle",
                active_volume: "0.3",
                technique: "Bolus",
                alert: true,
                alert_reason: "A. Mental",
            },
            purpose: "Chin Projection",
        },
        {
            id: "C4",
            name: "Pogônio (Soft Tissue)",
            indices: { right: 199, left: 199 },
            clinical: {
                depth: "Subcutâneo",
                tool: "Needle",
                active_volume: "0.3",
                technique: "Bolus",
                alert: false,
            },
            purpose: "Forward Projection",
        },
        {
            id: "C5",
            name: "Mento Lateral Inferior",
            indices: { right: 210, left: 430 },
            clinical: { depth: "Supraperiosteal", tool: "Needle", active_volume: "0.3", technique: "Bolus", alert: false },
            purpose: "Chin Widening",
        },
        {
            id: "C6",
            name: "Mento Lateral",
            indices: { right: 136, left: 365 },
            clinical: { depth: "Subcutâneo", tool: "Cannula", active_volume: "0.5", technique: "Cannula", alert: false },
            purpose: "Chin Widening",
        },
        {
            id: "Jw1",
            name: "Ângulo da Mandíbula",
            indices: { right: [169, 215], left: [397, 435] },
            clinical: {
                depth: "Supraperiosteal",
                tool: "Needle",
                active_volume: "0.5",
                technique: "Bolus",
                alert: false,
            },
            purpose: "Jawline Definition",
        },
        {
            id: "Jw2",
            name: "Área Pré-auricular",
            indices: { right: [93, 176], left: [323, 401] },
            clinical: {
                depth: "Subcutâneo",
                tool: "Cannula",
                active_volume: "0.5",
                technique: "Cannula",
                alert: true,
                alert_reason: "G. Parótida",
            },
            purpose: "Pre-auricular Deficit",
        },
        {
            id: "Jw3",
            name: "Corpo da Mandíbula",
            indices: { right: [58, 135], left: [288, 364] },
            clinical: {
                depth: "Subcutâneo",
                tool: "Cannula",
                active_volume: "1.0",
                technique: "Cannula",
                alert: true,
                alert_reason: "A. Facial",
            },
            purpose: "Jawline Topography",
        },
        {
            id: "Jw4",
            name: "Prejowl Inferior",
            indices: { right: 202, left: 422 },
            clinical: { depth: "Subcutâneo", tool: "Cannula", active_volume: "0.5", technique: "Cannula", alert: false },
            purpose: "Prejowl Camouflage",
        },
        {
            id: "Jw5",
            name: "Mento Anterior Inf.",
            indices: { right: 148, left: 377 },
            clinical: { depth: "Subcutâneo", tool: "Cannula", active_volume: "0.5", technique: "Cannula", alert: false },
            purpose: "Chin and Jawline Transition",
        },
    ],
    refinement: [

        {
            id: "NL1",
            name: "Upper Nasolabial",
            indices: { right: 203, left: 423 },
            clinical: {
                depth: "Subcutaneous/Deep Dermal",
                tool: "Cannula",
                active_volume: "0.3 - 0.5",
                technique: "Linear/Fanning",
                alert: true,
                alert_reason: "Facial Artery/Nasal Flare",
            },
            purpose: "Nasolabial Folds",
        },
        {
            id: "NL2",
            name: "Mid Nasolabial",
            indices: { right: 206, left: 426 },
            clinical: {
                depth: "Subcutaneous",
                tool: "Cannula",
                active_volume: "0.3",
                technique: "Linear",
                alert: false,
            },
            purpose: "Nasolabial Folds",
        },
        {
            id: "NL3",
            name: "Lower Nasolabial",
            indices: { right: 216, left: 436 },
            clinical: {
                depth: "Subcutaneous",
                tool: "Cannula",
                active_volume: "0.3",
                technique: "Linear",
                alert: false,
            },
            purpose: "Nasolabial Folds",
        },
        {
            id: "M1",
            name: "Marionette Upper",
            indices: { right: 202, left: 422 },
            clinical: {
                depth: "Subcutaneous",
                tool: "Cannula",
                active_volume: "0.3",
                technique: "Linear",
                alert: true,
                alert_reason: "Modiolus",
            },
            purpose: "Oral Commissure Support",
        },
        {
            id: "M2",
            name: "Marionette Mid",
            indices: { right: 210, left: 430 },
            clinical: {
                depth: "Subcutaneous",
                tool: "Cannula",
                active_volume: "0.3",
                technique: "Fanning",
                alert: false,
            },
            purpose: "Marionette Lines",
        },
        {
            id: "M3",
            name: "Marionette Lower",
            indices: { right: 394, left: 394 },
            clinical: {
                depth: "Subcutaneous",
                tool: "Cannula",
                active_volume: "0.3",
                technique: "Fanning",
                alert: false,
            },
            purpose: "Marionette Lines",
        },

        {
            id: "E1",
            name: "Cauda da Sobrancelha",
            indices: { right: 70, left: 300 },
            clinical: { depth: "ROOF", tool: "Cannula", active_volume: "0.2", technique: "Cannula", alert: false },
            purpose: "Lateral Brow Lift",
        },
        {
            id: "E2",
            name: "Centro da Sobrancelha",
            indices: { right: 105, left: 334 },
            clinical: { depth: "ROOF", tool: "Cannula", active_volume: "0.2", technique: "Cannula", alert: true, alert_reason: "Forame Supraorbital" },
            purpose: "Mid Brow Lift",
        },
        {
            id: "E3",
            name: "Cabeça da Sobrancelha",
            indices: { right: [107, 66], left: [336, 296] },
            clinical: { depth: "ROOF", tool: "Cannula", active_volume: "0.1", technique: "Cannula", alert: true, alert_reason: "Forame Supratroclear" },
            purpose: "Medial Brow",
        },
        {
            id: "O1",
            name: "Lateral Central Orbital",
            indices: { right: 143, left: 372 },
            clinical: { depth: "Supraperiosteal", tool: "Cannula", active_volume: "0.2", technique: "Cannula", alert: true, alert_reason: "Pálpebra Inferior" },
            purpose: "Orbital Support",
        },
        {
            id: "O2",
            name: "Lateral Inferior Orbital",
            indices: { right: 111, left: 340 },
            clinical: { depth: "Supraperiosteal", tool: "Cannula", active_volume: "0.2", technique: "Cannula", alert: true, alert_reason: "Pálpebra Inferior" },
            purpose: "Orbital Support",
        },
        {
            id: "O3",
            name: "Lateral Superior Orbital",
            indices: { right: 139, left: 368 },
            clinical: { depth: "Supraperiosteal", tool: "Cannula", active_volume: "0.1", technique: "Cannula", alert: true, alert_reason: "Pálpebra Superior" },
            purpose: "Orbital Support",
        },
        {
            id: "Tt1",
            name: "Infraorbital Central",
            indices: { right: 230, left: 450 },
            clinical: { depth: "Supraperiosteal", tool: "Cannula", active_volume: "0.2", technique: "Cannula", alert: true, alert_reason: "A. Infraorbital" },
            purpose: "Tear Trough Correction",
        },
        {
            id: "Tt2",
            name: "Infraorbital Lateral",
            indices: { right: 228, left: 448 },
            clinical: { depth: "Supraperiosteal", tool: "Cannula", active_volume: "0.2", technique: "Cannula", alert: false },
            purpose: "Tear Trough Support",
        },
        {
            id: "Tt3",
            name: "Infraorbital Medial",
            indices: { right: 232, left: 452 },
            clinical: { depth: "Supraperiosteal", tool: "Cannula", active_volume: "0.1", technique: "Cannula", alert: true, alert_reason: "A. Angular" },
            purpose: "Lid-Cheek Junction",
        },
        {
            id: "G1",
            name: "Glabela Lateral",
            indices: { right: 107, left: 336 },
            clinical: { depth: "Supraperiosteal", tool: "Cannula", active_volume: "0.1", technique: "Cannula", alert: true, alert_reason: "A. Supratroclear" },
            purpose: "Glabellar Lines",
        },
        {
            id: "G2",
            name: "Glabela Central",
            indices: { right: 8, left: 8 },
            clinical: { depth: "Supraperiosteal", tool: "Cannula", active_volume: "0.3", technique: "Cannula", alert: true, alert_reason: "Neurovasc. Glabelar" },
            purpose: "Glabellar Volumization",
        },
        {
            id: "NL1",
            name: "Sulco Nasolabial Sup.",
            indices: { right: 203, left: 423 },
            clinical: { depth: "Supraperiosteal", tool: "Needle", active_volume: "0.3", technique: "Needle", alert: true, alert_reason: "A. Facial (Fossa Canina)" },
            purpose: "Nasolabial Folds",
        },
        {
            id: "NL2",
            name: "Sulco Nasolabial Med.",
            indices: { right: 206, left: 426 },
            clinical: { depth: "Subcutâneo", tool: "Cannula", active_volume: "0.2", technique: "Cannula", alert: true, alert_reason: "A. Facial" },
            purpose: "Nasolabial Folds",
        },
        {
            id: "NL3",
            name: "Sulco Nasolabial Inf.",
            indices: { right: 216, left: 436 },
            clinical: { depth: "Subcutâneo", tool: "Cannula", active_volume: "0.2", technique: "Cannula", alert: true, alert_reason: "A. Facial" },
            purpose: "Nasolabial Folds",
        },
        {
            id: "M1",
            name: "Marionete Superior",
            indices: { right: 212, left: 432 },
            clinical: { depth: "Subdérmico", tool: "Needle", active_volume: "0.2", technique: "Needle", alert: false },
            purpose: "Oral Commissure Support",
        },
        {
            id: "M2",
            name: "Marionete Central",
            indices: { right: 208, left: 428 },
            clinical: { depth: "Subdérmico", tool: "Needle", active_volume: "0.2", technique: "Needle", alert: false },
            purpose: "Marionette Lines",
        },

        {
            id: "Lp1",
            name: "Vermilion Body",
            indices: { right: [14, 17], left: [13, 0] },
            clinical: { depth: "Submucosa", tool: "Cannula", active_volume: "0.2", technique: "Cannula", alert: false },
            purpose: "Lip Volumizing",
        },
        {
            id: "Lp2",
            name: "Arco de Cupido",
            indices: { right: 267, left: 37 },
            clinical: { depth: "Mucosa", tool: "Needle", active_volume: "0.05", technique: "Needle", alert: false },
            purpose: "Cupid's Bow Definition",
        },
        {
            id: "Lp3",
            name: "Borda Labial",
            indices: { right: 291, left: 61 },
            clinical: { depth: "Mucosa", tool: "Needle", active_volume: "0.15", technique: "Needle", alert: false },
            purpose: "Lip Border Definition",
        },
        {
            id: "Lp4",
            name: "Tubérculo Medial",
            indices: { right: 0, left: 0 },
            clinical: { depth: "Mucosa", tool: "Needle", active_volume: "0.1", technique: "Needle", alert: true, alert_reason: "A. Labial Superior" },
            purpose: "Medial Tubercle Projection",
        },
        {
            id: "Lp5",
            name: "Tubérculos Laterais",
            indices: { right: 267, left: 37 },
            clinical: { depth: "Mucosa", tool: "Needle", active_volume: "0.05", technique: "Needle", alert: true, alert_reason: "A. Labial Inferior" },
            purpose: "Lateral Tubercle Projection",
        },
        {
            id: "Lp6",
            name: "Comissura Oral",
            indices: { right: 291, left: 61 },
            clinical: { depth: "Mucosa", tool: "Needle", active_volume: "0.1", technique: "Needle", alert: false },
            purpose: "Oral Commissure Support",
        },
        {
            id: "Lp7",
            name: "Coluna do Filtro",
            indices: { right: 267, left: 37 },
            clinical: { depth: "Subdérmico", tool: "Needle", active_volume: "0.05", technique: "Needle", alert: false },
            purpose: "Philtrum Column Definition",
        },
        {
            id: "N1",
            name: "Espinha Nasal Ant.",
            indices: { right: 164, left: 164 },
            clinical: { depth: "Supraperiosteal", tool: "Needle", active_volume: "0.3", technique: "Needle", alert: false },
            purpose: "Nasal Spine Support",
        },
        {
            id: "N2",
            name: "Columela",
            indices: { right: 1, left: 1 },
            clinical: { depth: "Cartilagem", tool: "Needle", active_volume: "0.2", technique: "Needle", alert: false },
            purpose: "Columellar Support",
        },
        {
            id: "N3",
            name: "Ângulo Frontonasal",
            indices: { right: 168, left: 168 },
            clinical: { depth: "Supraperiosteal", tool: "Needle", active_volume: "0.3", technique: "Needle", alert: false },
            purpose: "Frontonasal Angle",
        },
        {
            id: "N4",
            name: "Dorso Ósseo",
            indices: { right: 197, left: 197 },
            clinical: { depth: "Supraperiosteal", tool: "Needle", active_volume: "0.2", technique: "Needle", alert: false },
            purpose: "Bony Dorsum",
        },
        {
            id: "N5",
            name: "Dorso Cartilaginoso",
            indices: { right: 5, left: 5 },
            clinical: { depth: "Cartilagem", tool: "Needle", active_volume: "0.2", technique: "Needle", alert: false },
            purpose: "Cartilaginous Dorsum",
        },
    ],
};
